version: '3.9'

x-base_service: &base_service
    ports:
      - "3600:7860"
    volumes:
      - &v1 /home/ubuntu/efs/data:/data
      - &v2 ./output:/output
      - &v3 ./config:/data/config
    stop_signal: SIGKILL
    tty: true
    restart: always
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [compute, utility]
        limits:
          memory: 55000M

name: webui-docker

services:
  download:
    build: ./services/download/
    profiles: ["download"]
    volumes:
      - *v1

  auto: &automatic
    <<: *base_service
    profiles: ["auto"]
    build: ./services/AUTOMATIC1111
    image: sd-auto:72
    environment:
      - SAFETENSORS_FAST_GPU=1
      - CLI_ARGS=--allow-code --xformers --gradio-auth=kiki:ilios101 --api-auth=kiki:ilios101 --enable-insecure-extension-access --no-hashing --api --cors-allow-origins=* --ckpt /data/models/Stable-diffusion/colorful_v31.safetensors --ckpt /data/models/Stable-diffusion/elegantEntropy_v14.safetensors --ckpt /data/models/Stable-diffusion/dreamshaperXL_turboDpmppSDE.safetensors --ckpt /data/models/Stable-diffusion/colorful_v31.safetensors
        # --nowebui

  auto-cpu:
    <<: *automatic
    profiles: ["auto-cpu"]
    deploy: {}
    environment:
      - CLI_ARGS=--no-half --precision full --allow-code --enable-insecure-extension-access --api

  invoke: &invoke
    <<: *base_service
    profiles: ["invoke"]
    build: ./services/invoke/
    image: sd-invoke:30
    environment:
      - PRELOAD=true
      - CLI_ARGS=--xformers

  # invoke-cpu:
  #   <<: *invoke
  #   profiles: ["invoke-cpu"]
  #   environment:
  #     - PRELOAD=true
  #     - CLI_ARGS=--always_use_cpu

  comfy: &comfy
    <<: *base_service
    profiles: ["comfy"]
    build: ./services/comfy/
    image: sd-comfy:6
    environment:
      - CLI_ARGS=


  comfy-cpu:
    <<: *comfy
    profiles: ["comfy-cpu"]
    deploy: {}
    environment:
      - CLI_ARGS=--cpu
